### ISSUE TITLE
Name for this project (vote)

### ISSUE THREAD

**Issue by shanoaice** [Shadowsocks-NET/v2ray-go#9]
submit your proposal for the name of this project in the comments. vote via emoji.
if you wish to keep the current name `v2ray-go`, vote for this comment.

**Comment by shanoaice** [comment]
v2go

**Comment by Lynnumu** [comment]
v2ray-mod

**Comment by Lynnumu** [comment]
v2ray-part, part means particular

**Comment by fjn308** [comment]
**v2re**

Cited from Oxford Advanced Learner's Dictionary:
> ray /reɪ/ noun
> (4) (also re) (music) the second note of a major scale
> 
> re /reɪ/
> (1) = ray (4)
> 
> re- /ri/ prefix
> (in verbs and related nouns, adjectives and adverbs) again

I notice that in 9/19 of the additional features, the description begeins with a "re-". As the second note of a musical major scale (do, re, mi, ...), "re" has an equal pronunciation to "ray", that is, they sound to be same but not exactly.

**Comment by fjn308** [comment]
v2ray-fork, no description is needed.
